package Me

type Controllers struct {
	ObjectName                  string              `json:"object-name"`
	Meta                        string              `json:"meta"`
	DurableID                   string              `json:"durable-id"`
	ControllerID                string              `json:"controller-id"`
	ControllerIDNumeric         int                 `json:"controller-id-numeric"`
	SerialNumber                string              `json:"serial-number"`
	HardwareVersion             string              `json:"hardware-version"`
	CpldVersion                 string              `json:"cpld-version"`
	MacAddress                  string              `json:"mac-address"`
	NodeWwn                     string              `json:"node-wwn"`
	IPAddress                   string              `json:"ip-address"`
	IPSubnetMask                string              `json:"ip-subnet-mask"`
	IPGateway                   string              `json:"ip-gateway"`
	IP6LinkLocalAddress         string              `json:"ip6-link-local-address"`
	IP6LinkLocalGateway         string              `json:"ip6-link-local-gateway"`
	IP6AutoAddress              string              `json:"ip6-auto-address"`
	IP6AutoAddressSource        string              `json:"ip6-auto-address-source"`
	IP6AutoAddressSourceNumeric int                 `json:"ip6-auto-address-source-numeric"`
	IP6AutoGateway              string              `json:"ip6-auto-gateway"`
	IP61Address                 string              `json:"ip61-address"`
	IP61Gateway                 string              `json:"ip61-gateway"`
	IP62Address                 string              `json:"ip62-address"`
	IP62Gateway                 string              `json:"ip62-gateway"`
	IP63Address                 string              `json:"ip63-address"`
	IP63Gateway                 string              `json:"ip63-gateway"`
	IP64Address                 string              `json:"ip64-address"`
	IP64Gateway                 string              `json:"ip64-gateway"`
	Disks                       int                 `json:"disks"`
	NumberOfStoragePools        int                 `json:"number-of-storage-pools"`
	VirtualDisks                int                 `json:"virtual-disks"`
	CacheMemorySize             int                 `json:"cache-memory-size"`
	SystemMemorySize            int                 `json:"system-memory-size"`
	HostPorts                   int                 `json:"host-ports"`
	DriveChannels               int                 `json:"drive-channels"`
	DriveBusType                string              `json:"drive-bus-type"`
	DriveBusTypeNumeric         int                 `json:"drive-bus-type-numeric"`
	Status                      string              `json:"status"`
	StatusNumeric               int                 `json:"status-numeric"`
	FailedOver                  string              `json:"failed-over"`
	FailedOverNumeric           int                 `json:"failed-over-numeric"`
	FailOverReason              string              `json:"fail-over-reason"`
	FailOverReasonNumeric       int                 `json:"fail-over-reason-numeric"`
	ScFw                        string              `json:"sc-fw"`
	Vendor                      string              `json:"vendor"`
	Model                       string              `json:"model"`
	PlatformType                string              `json:"platform-type"`
	PlatformTypeNumeric         int                 `json:"platform-type-numeric"`
	Multicore                   string              `json:"multicore"`
	MulticoreNumeric            int                 `json:"multicore-numeric"`
	ScCPUType                   string              `json:"sc-cpu-type"`
	ScCPUSpeed                  int                 `json:"sc-cpu-speed"`
	InternalSerialNumber        string              `json:"internal-serial-number"`
	CacheLock                   string              `json:"cache-lock"`
	CacheLockNumeric            int                 `json:"cache-lock-numeric"`
	WritePolicy                 string              `json:"write-policy"`
	WritePolicyNumeric          int                 `json:"write-policy-numeric"`
	Description                 string              `json:"description"`
	PartNumber                  string              `json:"part-number"`
	Revision                    string              `json:"revision"`
	DashLevel                   string              `json:"dash-level"`
	FruShortname                string              `json:"fru-shortname"`
	MfgDate                     string              `json:"mfg-date"`
	MfgDateNumeric              int                 `json:"mfg-date-numeric"`
	MfgLocation                 string              `json:"mfg-location"`
	MfgVendorID                 string              `json:"mfg-vendor-id"`
	LocatorLed                  string              `json:"locator-led"`
	LocatorLedNumeric           int                 `json:"locator-led-numeric"`
	SsdAltPathIoCount           int                 `json:"ssd-alt-path-io-count"`
	Health                      string              `json:"health"`
	HealthNumeric               int                 `json:"health-numeric"`
	HealthReason                string              `json:"health-reason"`
	HealthRecommendation        string              `json:"health-recommendation"`
	Position                    string              `json:"position"`
	PositionNumeric             int                 `json:"position-numeric"`
	Rotation                    string              `json:"rotation"`
	RotationNumeric             int                 `json:"rotation-numeric"`
	PhyIsolation                string              `json:"phy-isolation"`
	PhyIsolationNumeric         int                 `json:"phy-isolation-numeric"`
	RedundancyMode              string              `json:"redundancy-mode"`
	RedundancyModeNumeric       int                 `json:"redundancy-mode-numeric"`
	RedundancyStatus            string              `json:"redundancy-status"`
	RedundancyStatusNumeric     int                 `json:"redundancy-status-numeric"`
	NetworkParameters           []NetworkParameters `json:"network-parameters"`
	Port                        []Ports             `json:"port"`
	ExpanderPorts               []ExpanderPorts     `json:"expander-ports"`
	CompactFlash                []CompactFlash      `json:"compact-flash"`
	Expanders                   []Expanders         `json:"expanders"`
}
